version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 14
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli 
  build:
    commands:
      - | 
        GIT_BRANCH="$(git symbolic-ref HEAD --short 2>/dev/null)"
        if [ "$GIT_BRANCH" = "" ] ; then
          GIT_BRANCH="$(git rev-parse HEAD | xargs git name-rev | cut -d' ' -f2 | sed 's/remotes\/origin\///g')";
        fi
      - echo GIT_BRANCH - $GIT_BRANCH
      - |
        if ["$GIT_BRANCH" == "master"] ; then
          echo Build started on `date`;
          ng build;
        elif ["$GIT_BRANCH" != "master"]; then
          echo Test started on `date`;
          ng test;
        fi
      - echo Compiling the Node.js code
  post_build:
    commands:
      - |
        if ["$GIT_BRANCH" == "master"] ; then
          cp . results/.
        fi
      - echo Build completed on `date`
artifacts:
  files:
    "results/**/*"